apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: breakable
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/initial-scale: "1"
    spec:
      containers:
      - image: ko://KauzClay/useful-yamls/apps/breakable
        env:
        - name: TARGET
          value: "Go Sample v1"
