apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: yeti
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: projects.registry.vmware.com/tanzu_serverless/hello-yeti:latest
