#@ load("@ytt:data", "data")

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: #@ data.values.name
 namespace: #@ data.values.name
spec:
 template:
  spec:
   containers:
    - image: gcr.io/knative-samples/helloworld-go
      env:
        - name: TARGET
          value: #@ "{}".format(data.values.name)
