#!/bin/bash

cat <<EOT | ytt -f /Users/pivotal/daisy/useful-yamls/knative/ksvc-template.yaml --data-value name=$1 | kubectl apply -f -
#@ load("@ytt:data", "data")

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: #@ data.values.name
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: gcr.io/knative-samples/helloworld-go
      env:
        - name: TARGET
          value: #@ "{}".format(data.values.name)

EOT
