apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: ko://examples/debug
        name: debug
        ports:
        - containerPort: 8080
        env:
        - name: MY_VAR
          value: "blue"
        - name: REQUEST_URL
          value: "http://red.default.tanzu.biz/env"
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blue
  sessionAffinity: None
  type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: blue
#   labels:
#     app: blue
# spec:
#   defaultBackend:
#     service:
#       name: blue
#       port:
#         number: 80
