---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/workload-type: server
  name: debug
  namespace: default
spec:
  source:
    subPath: apps/debug
    git:
      url: https://github.com/KauzClay/useful-yamls.git
      ref:
        branch: main
  params:
  - name: carvel_package_gitops_subpath
    value: tanzu/tap/gitops
  - name: carvel_package_name_suffix
    value: kauz
