---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  # Secret names are always required.
  secretName: test-cert
  duration: 2160h # 90d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - app.claytest.tanzu.biz
  ipAddresses:
    - 34.170.98.68
  # Issuer references are always required.
  issuerRef:
    name: tap-ingress-selfsigned
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: test-cert
spec:
  delegations:
    - secretName: test-cert
      targetNamespaces:
      - "*"
