---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: test-cert
  namespace: dog
spec:
  toNamespace: default

#! allow user-password to be created in user2 namespace
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: test-cert
  namespace: default
spec:
  fromNamespace: dog
