apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: hello
 namespace: default
spec:
 template:
  spec:
   containers:
   - image: ko://examples/hello
     env:
     - name: TARGET
       value: "folks"
